# Generated by Django 4.2.2 on 2023-06-09 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0002_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='pokemon',
            field=models.ManyToManyField(related_name='pokemon_list', to='fantasy.pokemon'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_of_poke', to='fantasy.trainer'),
        ),
    ]
