# Generated by Django 4.2.2 on 2023-06-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0003_trainer_pokemon_alter_pokemon_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='pokemon',
        ),
    ]
