# Generated by Django 4.2.2 on 2023-06-16 02:17

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0004_remove_trainer_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.trainer'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'pending'), (2, 'invalid'), (3, 'valid'), (4, 'rejected'), (5, 'fulfilled')], max_length=1),
        ),
    ]
